
// src/context/types.js
// Auth types
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const CLEAR_ERRORS = "CLEAR_ERRORS";


// Resource subscription types
export const RESOURCE_SIGNUP_SUCCESS = "RESOURCE_SIGNUP_SUCCESS";
export const RESOURCE_SIGNUP_FAIL = "RESOURCE_SIGNUP_FAIL";


// Blog types
export const GET_BLOGS = "GET_BLOGS";
export const GET_BLOG = "GET_BLOG";
export const GET_POPULAR_BLOGS = "GET_POPULAR_BLOGS";
export const GET_RELATED_BLOGS = "GET_RELATED_BLOGS";
export const CREATE_BLOG = "CREATE_BLOG";
export const UPDATE_BLOG = "UPDATE_BLOG";
export const DELETE_BLOG = "DELETE_BLOG";
export const BLOG_ERROR = "BLOG_ERROR";
export const CLEAR_BLOG_ERROR = "CLEAR_BLOG_ERROR";
export const SET_LOADING = "SET_LOADING";
export const CLEAR_BLOG = "CLEAR_BLOG";
export const ADD_COMMENT = "ADD_COMMENT";
export const TOGGLE_LIKE = "TOGGLE_LIKE";
export const GET_BLOG_ANALYTICS = "GET_BLOG_ANALYTICS";
export const GET_TRENDING_TOPICS = "GET_TRENDING_TOPICS";
export const GET_RECOMMENDATIONS = "GET_RECOMMENDATIONS";
export const SET_SEARCH_RESULTS = "SET_SEARCH_RESULTS";
export const CLEAR_SEARCH_RESULTS = "CLEAR_SEARCH_RESULTS";
// Socket types
export const SOCKET_CONNECTED = "SOCKET_CONNECTED";
export const SOCKET_DISCONNECTED = "SOCKET_DISCONNECTED";
export const UPDATE_ONLINE_USERS = "UPDATE_ONLINE_USERS";



// Course Types
export const CREATE_COURSE = "CREATE_COURSE";
export const UPDATE_COURSE = "UPDATE_COURSE";
export const GET_COURSES = "GET_COURSES";
export const GET_COURSE = "GET_COURSE";
export const COURSE_ERROR = "COURSE_ERROR";
export const CLEAR_COURSE_ERROR = "CLEAR_COURSE_ERROR";
export const GET_COURSE_PROGRESS = "GET_COURSE_PROGRESS";
export const GET_DASHBOARD_STATS = "GET_DASHBOARD_STATS";
